# Generated by Django 3.2.15 on 2022-08-26 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='В избранном'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото блюда'),
        ),
    ]
