# Generated by Django 3.2.15 on 2022-08-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220826_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'ordering': ['-id'], 'verbose_name': 'Ингредиент связанный', 'verbose_name_plural': 'Ингредиенты связанные'},
        ),
    ]
