# Generated by Django 3.2.15 on 2022-08-28 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscribe',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
